name: cash_api
version: 1.0.0
description: Api for cash api.
homepage: https://github.com/jiejie-dev/cash-api-dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: '^5.2.0'
  json_annotation: '^4.4.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^6.1.5'
  test: ^1.16.0
